#############################################
Mongo:
  Database: Practice
  URL: mongodb://127.0.0.1:27017/Practice
#############################################
Practice:
  Spawn: world:108.42862345557752:106.0:2.4753712094583005:-89.59775:0.17956273
  Performance-mode: true
  Core-Hook: true
  HCF-Enabled: false
#############################################
Queue-Lore:
- "&7&m----------------------"
- "&fIn Queue: &b{in_queue}"
- "&fIn Fight: &b{in_fight}"
- ""
- "&bClick to join queue."
- "&7&m----------------------"
#############################################
MOTD:
  enabled: true
  lines:
  - "&7&m------------------------------------------------"
  - "&bPractice"
  - "&7&m------------------------------------------------"
  - "&bPractice Commands:"
  - "&7/duel <Name> &8- &7Send a player a duel request"
  - "&7/spec <Name> &8- &7Spectate a player's ongoing match"
  - "&7/settings &8- &7Edit preferences on the server"
  - "&7/party &8- &7See all party related commands"
  - " "
  - "&7To send a message to your party do &7'&d@&7' <message>:"
  - " "
  - "&bServer Links:"
  - "&7Website &8- &bwww.duels.us"
  - "&7Discord &8- &bdiscord.gg/duelsus"
  - "&7Store &8- &bstore.duels.us"
  - " "
  - "&7Welcome to the &bPractice!"
  - "&7&m------------------------------------------------"
#############################################
Ranked:
  Enabled: true
  Require-Kills: false
  Required-Kills: 10
#############################################
SCOREBOARD:
  HEADER: "&b&lNA Practice"
  FOOTER: "&7&oduels.us"
  BAR: "-------------------"
#############################################
LINKS:
  STORE: "https://store.duels.us/"
#############################################