name: Practice
main: dev.liquidnetwork.liquidpractice.LiquidPractice
version: ${project.version}
depend:
  - ProtocolLib
softdepend:
  - HolographicDisplays
  - PlaceholderAPI
  - MizuCore
  - ZoomCore
  - AquaCore
  - Hestia